[package]
name = 'asapr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'asapr'

[dependencies]
extendr-api = '*'
asap = {git="https://github.com/Luke-ebbis/rust-asap", branch = "master"}
